"use client";
import React from "react";
import Button from "@/components/ui/button/Button";
import CodeOfConductText from "@/components/auth/consent/CodeOfConductText";
import DataConsentText from "@/components/auth/consent/DataConsentText";
import { formatCohortLongDate } from "@/lib/datetime";
import type { FellowConsentRow } from "@/lib/api/consents.server";

/**
 * Printable per-fellow consent document. Renders the full text of
 * both forms followed by the typed-signature block captured at
 * acceptance time. Admins click Print → browser's "Save as PDF"
 * is the canonical archive flow.
 */
export default function ConsentDocumentView({
  consent,
}: {
  consent: FellowConsentRow;
}) {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8 print:px-0 print:py-0">
      {/* Action bar — hidden in print */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-xl font-bold text-gray-800">
            Consent document — {consent.fullName}
          </h1>
          <p className="mt-1 text-sm text-gray-500">{consent.email}</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() =>
              typeof window !== "undefined" && window.history.back()
            }
          >
            Back
          </Button>
          <Button
            variant="fellowship"
            size="sm"
            onClick={() =>
              typeof window !== "undefined" && window.print()
            }
            className="bg-fellowship-navy! text-white! hover:bg-fellowship-navy-dark!"
          >
            Print / Save as PDF
          </Button>
        </div>
      </div>

      <article className="space-y-10 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm print:rounded-none print:border-0 print:p-0 print:shadow-none">
        {/* Code of Conduct */}
        <section>
          <CodeOfConductText />
          <SignatureBlock
            heading="Declaration — Code of Conduct"
            name={consent.consentSignatureName ?? consent.fullName}
            country={consent.consentCountry ?? consent.country ?? "—"}
            signedAt={consent.codeOfConductAcceptedAt}
          />
        </section>

        <hr className="border-gray-200 print:border-gray-400" />

        {/* Data Protection */}
        <section>
          <DataConsentText />

          <div className="mt-6 rounded-lg border border-gray-200 bg-gray-50 p-4 print:bg-transparent">
            <p className="text-sm font-semibold text-gray-800">
              Recorded preferences
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-gray-700">
              <li>
                Session recordings:{" "}
                <strong>
                  {consent.consentRecordingOptIn
                    ? "Consents to being recorded."
                    : "Does not consent to being recorded where avoidable."}
                </strong>
              </li>
              <li>
                Fellowship communications:{" "}
                <strong>
                  {consent.consentCommsOptIn
                    ? "Consents to fellowship emails, updates, and opportunities."
                    : "Declines fellowship-related emails."}
                </strong>
              </li>
              <li>
                Alumni communications:{" "}
                <strong>
                  {consent.consentAlumniCommsOptIn
                    ? "Consents to alumni communications after programme completion."
                    : "Declines alumni communications."}
                </strong>
              </li>
            </ul>
          </div>

          <SignatureBlock
            heading="Declaration — Data Protection Consent"
            name={consent.consentSignatureName ?? consent.fullName}
            country={consent.consentCountry ?? consent.country ?? "—"}
            signedAt={consent.dataConsentAcceptedAt}
          />
        </section>
      </article>

      <p className="mt-6 text-center text-xs text-gray-500 print:mt-2">
        Generated by the AI Fellows LMS administrative console. Fellow ID:{" "}
        <span className="font-mono">{consent.id}</span>
      </p>

      {/* Browser print sizing — same trick the certificate print page uses */}
      <style>{`
        @page { size: A4 portrait; margin: 16mm; }
        @media print {
          html, body { margin: 0 !important; padding: 0 !important; background: white !important; }
        }
      `}</style>
    </div>
  );
}

function SignatureBlock({
  heading,
  name,
  country,
  signedAt,
}: {
  heading: string;
  name: string;
  country: string;
  signedAt: string | null;
}) {
  return (
    <div className="mt-8 rounded-lg border border-gray-300 bg-white p-5">
      <p className="text-sm font-semibold text-gray-800">{heading}</p>
      {signedAt ? (
        <p className="mt-1 text-sm text-gray-600">
          I acknowledge that I have read, understood, and agree to comply with
          this document.
        </p>
      ) : (
        <p className="mt-1 text-sm text-warning-700">
          This fellow has not yet signed this document.
        </p>
      )}
      <dl className="mt-4 grid grid-cols-1 gap-x-6 gap-y-2 text-sm sm:grid-cols-2">
        <Row label="Full name" value={name} />
        <Row label="Country" value={country} />
        <Row
          label="Signed at (WAT)"
          value={signedAt ? formatCohortLongDate(signedAt) : "—"}
        />
        <Row
          label="Signature"
          value={
            signedAt
              ? `${name} (typed signature)`
              : "—"
          }
          mono
        />
      </dl>
    </div>
  );
}

function Row({
  label,
  value,
  mono = false,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div className="flex flex-col">
      <dt className="text-xs font-medium uppercase tracking-wide text-gray-500">
        {label}
      </dt>
      <dd
        className={`text-gray-800 ${mono ? "font-mono text-sm" : "text-sm"}`}
      >
        {value}
      </dd>
    </div>
  );
}
